/**
 * Every screen's data, from one published snapshot.
 *
 * This module used to fan out eleven to fourteen requests per page against a
 * FastAPI service replaying a recorded September 2023 event, threading a
 * per-visitor `?at=` clock through each one. The replay is retired. There is
 * now a single static file, fetched once per session and shared by every
 * screen — see `lib/live/snapshot.ts`.
 *
 * **Mock mode has been removed.** It existed so the demo would survive a
 * free-tier backend asleep or unreachable; a static file on a CDN has neither
 * failure mode, and keeping three fixture modules in step with a schema that
 * now has to mirror the whole dashboard was a standing cost with no consumer.
 * For local work, point `NEXT_PUBLIC_HAZE_SNAPSHOT_URL` at a file produced by
 * `python scripts/07_live_snapshot.py --out <path>` and serve it.
 *
 * Failures are explicit. Loaders throw `SnapshotUnavailable`, and every screen
 * renders that reason. Nothing renders blank.
 */

import type { Channel, Institution, Notification } from "@/lib/api/types";
import {
  fetchSnapshot,
  findInstitution,
  SnapshotUnavailable,
  toAlertResponse,
  toForecast,
  toHealth,
  toHotspotSummary,
  toInstitutions,
  type LiveSnapshot,
  type SnapshotInstitution,
} from "@/lib/live/snapshot";
import type { StatusTimelinePoint } from "@/lib/ui/timeline";
import { createLocalNotification } from "./notification";

/**
 * Both products show a 24-hour outlook.
 *
 * This matched the backend's alert horizon (`config.FORECAST_HORIZON_HOURS`)
 * and still matches the snapshot's: the forecast carries exactly 24 points and
 * alerts are evaluated across all of them. At 12 every row rendered an ALERT
 * badge beside a peak below the 35.5 threshold, because nothing breaches inside
 * 12 hours — the alerts are generated by hours 13-24.
 */
export const LITE_HORIZON_HOURS = 24;
export const PRO_HORIZON_HOURS = 24;

async function requireSnapshot(): Promise<LiveSnapshot> {
  const result = await fetchSnapshot();
  if (!result.ok) throw new SnapshotUnavailable(result.reason);
  return result.snapshot;
}

/**
 * Institution context comes from the selector, not a login — there is no
 * authentication in this build.
 */
function resolveRecord(
  snapshot: LiveSnapshot,
  preferred: string | null | undefined,
  envVar: string | undefined,
  prefer?: (item: Institution) => boolean,
): SnapshotInstitution {
  const direct = findInstitution(snapshot, preferred);
  if (direct) return direct;

  const configured = findInstitution(snapshot, envVar?.trim() || null);
  if (configured) return configured;

  // Only schools and hospitals are addressable; `authority` sites exist in the
  // data but are not an institution-staff audience.
  const addressable = snapshot.institutions.filter(
    (i) => i.institution.type === "school" || i.institution.type === "hospital",
  );
  const pool = addressable.length ? addressable : snapshot.institutions;
  const match = (prefer && pool.find((i) => prefer(i.institution))) ?? pool[0];

  if (!match) {
    throw new SnapshotUnavailable("malformed");
  }
  return match;
}

/**
 * The alert states this snapshot records, newest first.
 *
 * One published snapshot is one observed instant, so this is a single point.
 * Workstream 3 replaces it with a reader over the archive of past snapshots;
 * the shape is already what that reader will return, so screens consuming it
 * do not change again.
 */
function timelineFrom(
  snapshot: LiveSnapshot,
  record: SnapshotInstitution,
): StatusTimelinePoint[] {
  return [{ at: snapshot.generated_at, alert: record.alert }];
}

function base(snapshot: LiveSnapshot, record: SnapshotInstitution) {
  return {
    at: snapshot.generated_at,
    generatedAt: snapshot.generated_at,
    issuedAt: snapshot.issued_at,
    issuedOffsetHours: snapshot.issued_offset_hours,
    health: toHealth(snapshot),
    institutions: toInstitutions(snapshot) as readonly Institution[],
    institution: record.institution,
    forecast: toForecast(record),
    alertResponse: toAlertResponse(record),
    statusTimeline: timelineFrom(snapshot, record),
  } as const;
}

// -- Lite -------------------------------------------------------------------

export async function loadLiteOverviewData(institutionId?: string | null) {
  const snapshot = await requireSnapshot();
  const record = resolveRecord(
    snapshot,
    institutionId,
    process.env.NEXT_PUBLIC_HAZE_INSTITUTION_ID,
  );
  return base(snapshot, record);
}

export async function loadLiteAlertHistoryData(institutionId?: string | null) {
  return loadLiteOverviewData(institutionId);
}

// -- Pro --------------------------------------------------------------------

export async function loadProLiveMonitorData() {
  const snapshot = await requireSnapshot();

  return {
    at: snapshot.generated_at,
    generatedAt: snapshot.generated_at,
    issuedAt: snapshot.issued_at,
    issuedOffsetHours: snapshot.issued_offset_hours,
    health: toHealth(snapshot),
    institutions: toInstitutions(snapshot) as readonly Institution[],
    forecasts: snapshot.institutions.map(toForecast),
    alerts: snapshot.institutions
      .map((i) => i.alert)
      .filter((a): a is NonNullable<typeof a> => Boolean(a)),
    hotspotSummary: toHotspotSummary(snapshot),
  } as const;
}

export async function loadProInstitutionDetailData(institutionId?: string | null) {
  const snapshot = await requireSnapshot();
  const record = resolveRecord(
    snapshot,
    institutionId,
    process.env.NEXT_PUBLIC_HAZE_PRO_INSTITUTION_ID,
    (item) => item.country === "MY",
  );

  return {
    ...base(snapshot, record),
    hotspotSummary: toHotspotSummary(snapshot),
  } as const;
}

/**
 * The screen renders three states and filters across all of them. Only "alert"
 * is derivable today: a published snapshot records whether an alert was in
 * force, and separating "safe" from "watch" needs the forecast as it stood at
 * that moment, which the archive will carry but the current record does not.
 * The union stays whole so the screen keeps its filters and its legend honest
 * about what it is looking for.
 */
export type ProHistoryStatus = "safe" | "watch" | "alert";

export type ProHistoryEvent = {
  id: string;
  timestamp: string;
  status: ProHistoryStatus;
  title: string;
  description: string;
  forecastPeak?: number;
  sourceArea?: string;
  direction?: string;
  transportHours?: number;
  notificationState: "prepared" | "sent" | "monitoring" | "none";
};

export async function loadProAlertHistoryData(institutionId?: string | null) {
  const base = await loadProInstitutionDetailData(institutionId);

  const historyEvents: ProHistoryEvent[] = base.statusTimeline
    .filter((point) => point.alert)
    .map((point) => {
      const alert = point.alert!;
      return {
        id: `${alert.alert_id}-${point.at}`,
        timestamp: point.at,
        status: "alert" as const,
        title: "Forecast alert in effect",
        description:
          `Forecast upper-band peak reached ${alert.forecast_peak_pm25.toFixed(1)} µg/m³ `
          + `with ${alert.lead_time_hours}h warning lead time.`,
        forecastPeak: alert.forecast_peak_pm25,
        sourceArea: alert.source_country ?? undefined,
        // Composed, not fetched. `transboundary` is on the alert and
        // `admin_region` on the institution, both already loaded. Phrased
        // exactly as the Haze Movement card on Institution Detail so the two
        // screens cannot disagree.
        direction: alert.transboundary
          ? `Cross-border transport toward ${base.institution.admin_region}`
          : `Transport within ${base.institution.admin_region}`,
        notificationState: "prepared" as const,
      };
    });

  return { ...base, historyEvents } as const;
}

export async function loadProNotificationPreviewData(institutionId?: string | null) {
  return loadProInstitutionDetailData(institutionId);
}

// -- Confirm & Send (simulated, local only) ---------------------------------

/**
 * Confirm & Send is **simulated only, and entirely local** in both Lite and Pro.
 *
 * It never calls a write endpoint. The record it returns exists only in React
 * state for the life of the page, so no click can mutate shared state. There is
 * no write path in this application at all.
 */
export function confirmNotification({
  institution,
  channel,
  language,
  previewMessage,
  alertId,
}: {
  institution: Institution;
  channel: Channel;
  language?: string | null;
  previewMessage: string;
  alertId?: string;
}): Notification {
  return createLocalNotification({
    institution,
    channel,
    message: previewMessage,
    language: language ?? institution.languages[0] ?? "en",
    alertId,
  });
}

/** Kept as named aliases so Lite and Pro screens read naturally. */
export const confirmLiteNotification = confirmNotification;
export const confirmProNotification = confirmNotification;
